Repository SkyOpsCloud/book-store, pull requests merged in 2025-02, with the labels that each got.

#9 feat: add buildspec.yml for the aws codebuild and switch to dynamodb from postgresql
  .gitignore
  backend/.gitignore
  backend/app.js
  backend/buildspec.yml
  backend/package.json
  backend/pnpm-lock.yaml
Labels: enhancement

#11 feat: init terraform
  backend/.gitignore
  backend/app.js
  backend/buildspec.yml
  backend/package.json
  backend/pnpm-lock.yaml
  terraform/main.tf
Labels: enhancement

#14 fix: correct db names and update terraform file
  backend/app.js
  terraform/main.tf
Labels: enhancement, fix

#19 chore: allow localhost origin for frontend development
  backend/app.js
  frontend/src/context/AuthContext.jsx
  frontend/src/pages/LogIn.jsx
  frontend/src/pages/home.jsx
  frontend/src/pages/register.jsx
Labels: enhancement

#20 fix: remove s3 bucket for images and adjust to use the openlibrary.org api
  backend/routes.js
  frontend/src/components/homeBookCard.jsx
  frontend/src/pages/bookPage.jsx
  terraform/main.tf
Labels: enhancement

#22 feat: reduce the number of reqs sends to lambda function using a custom react hook
  frontend/src/App.jsx
  frontend/src/context/BooksContext.jsx
  frontend/src/pages/home.jsx
Labels: enhancement

#25 docs(terraform): update README for new variable configuration
  terraform/README.md
Labels: documentation

#33 docs: update main README and mockdata.md
  README.md
  backend/mockdata.md
Labels: documentation, enhancement
